### PR TITLE
Yurapav99 lvnetzzz 105 uniform buttons

### PR DESCRIPTION
**Pull request by yurapav99**
add and use uniform button in settings and shedule screens
image
image

### CODE REVIEW

**Review by andriy-mudrak — COMMENTED** [review]
Why did you removed baseURL.js.example.js?

**Comment by yurapav99** [comment]
ops, already fix.

чт, 21 мар. 2019 г. в 00:52, andriy-mudrak <notifications@github.com>:

**Comment by andriy-mudrak** [comment]
Also I think that we have to use this button in PerformanceScreen

**Review by vtorkalo — DISMISSED** [review]

**Comment by vtorkalo** [comment]
Issue with upper case
https://stackoverflow.com/questions/24880388/cannot-lower-case-button-text-in-android-studio

**Review by vtorkalo — APPROVED** [review]

**Pull request merged**
